// Code generated by "stringer -type buttonID -trimprefix Button ."; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ButtonNew-0]
	_ = x[ButtonImport-1]
	_ = x[ButtonLoad-2]
	_ = x[ButtonSave-3]
	_ = x[ButtonRotate-4]
	_ = x[ButtonExit-5]
	_ = x[ButtonNextGif-6]
	_ = x[ButtonVSyncToggle-7]
}

const _buttonID_name = "NewImportLoadSaveRotateExitNextGifVSyncToggle"

var _buttonID_index = [...]uint8{0, 3, 9, 13, 17, 23, 27, 34, 45}

func (i buttonID) String() string {
	if i >= buttonID(len(_buttonID_index)-1) {
		return "buttonID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _buttonID_name[_buttonID_index[i]:_buttonID_index[i+1]]
}
